export const SeleneTheme = {
    colors: {
        purple: 0x7B1FA2,
        green: 0x43A047,
        grey: 0x757575,
        red: 0xD32F2F,
        blue: 0x1E88E5,
        twitter: 0x1DA1F2,
        instagram: 0xE1306C,
        tiktok: 0xFE2C55,
        bluesky: 0x0085FF,
        reddit: 0xFF4500,
    },
    prefixes: {
        player: '音楽プレイヤー',
        ping: 'レイテンシ計測',
        avatar: 'アバター表示',
        idle: ' 待機中 ',
        counter: 'カウンター',
        short: 'URL短縮',
        error: '⚠️ エラー ⚠️',
        embedfix: 'ツイート埋め込み',
        instagram: 'Instagram 埋め込み',
        tiktok: 'TikTok 埋め込み',
        bluesky: 'Bluesky 埋め込み',
        reddit: 'Reddit 埋め込み',
        ticket: 'チケットサポート',
        settings: 'サーバー設定',
        logger: 'ロガー設定',
        xp: '経験値設定',
        profile: 'プロフィール',
        levelup: 'レベルアップ',
    },
} as const;
